#!/bin/bash

echo "Creating link to bashrc"
rm ~/.bashrc
ln -s ~/Documents/repositories/settings/scripts/bashrc ~/.bashrc
source ~/.bashrc

echo "Creating link to openbox ~/Documents/repositories/settings/scripts"
mkdir -p ~/.config/openbox
rm ~/.config/openbox/rc.xml
rm ~/.config/openbox/autostart

ln -s ~/Documents/repositories/settings/scripts/openbox-rc.xml ~/.config/openbox/rc.xml
ln -s ~/Documents/repositories/settings/scripts/openbox-autostart ~/.config/openbox/autostart

echo "Creating link to conky script"
mkdir -p ~/.config/conky
rm ~/.config/conky/conkyrc
ln -s ~/Documents/repositories/settings/scripts/conkyrc ~/.config/conky/conkyrc

echo "Creating link to devilspie2 script"
mkdir -p ~/.config/devilspie2
rm ~/.config/devilspie2/devilspie2.lua
ln -s ~/Documents/repositories/settings/scripts/devilspie2.lua ~/.config/devilspie2/devilspie2.lua

echo "Creating link to tint2 script"
mkdir -p ~/.config/tint2
rm ~/.config/tint2/tint2rc
ln -s ~/Documents/repositories/settings/scripts/tint2rc ~/.config/tint2/tint2rc

