#!/bin/bash

#while IFS='' read -r line || [[ -n "$line" ]]; do
#    apm update $line
#done < "atom-packages"

while IFS='' read -r line || [[ -n "$line" ]]; do
    sudo zypper in -y $line
done < "system-packages"
