# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

source ~/Documents/repositories/configs/scripts/colors.sh

PS1="\[$bldcyn\]@\u \[$bldblk\]\W \[$txtrst\]\$ "

export JAVA_HOME=/usr/java/default
export WORKON_HOME=/home/msfernandes/Documents/virtualenvs
export PROJECT_HOME=/home/msfernandes/Documents/repositories
export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_SCRIPT=/usr/bin/virtualenvwrapper.sh
source /usr/bin/virtualenvwrapper_lazy.sh

alias django='python manage.py'

PATH="/usr/local/heroku/bin:$PATH"
PATH=$PATH:/home/msfernandes/Documents/google_appengine/
PATH=${PATH}:/home/msfernandes/Documents/android-sdk/platform-tools
PATH=${PATH}:/home/msfernandes/Documents/android-sdk/tools

eval $(thefuck --alias)
export PATH=~/.gem/ruby/1.9.1/bin:$PATH

